### ISSUE TITLE
Unable to push the collector - Build fails every time. 

### ISSUE THREAD

**Issue by vnl** [GoogleCloudPlatform/opentelemetry-cloud-run#15]
Hi All, 

Following the instructions, running the command `gcloud builds submit . --config=cloudbuild.yaml `always results in an error. The collector builds fine but cannot push it to the registry. 

It worked for the first time and then just refused to upload to the registry.  

After the first successful run, I ran the cleanup section to clear all the resources. 

![image](https://github.com/GoogleCloudPlatform/opentelemetry-cloud-run/assets/1355466/4175539a-6445-4edd-8f76-6cab24e42ed1)

**Comment by damemi** [comment]
Hi @vnl, just to check, are you able to consistently build and push following the [manual steps](https://github.com/GoogleCloudPlatform/opentelemetry-cloud-run?tab=readme-ov-file#build-and-run-manually)?

@ymotongpoo added the Cloud Build steps in https://github.com/GoogleCloudPlatform/opentelemetry-cloud-run/pull/4. Yoshi, are you able to help debug this issue?

**Comment by vnl** [comment]
okay another test, running - `export GCP_PROJECT=<project-id>` now played well and I am able to push. 
Just cloning and authenticating gcloud does not work straight away.

**Comment by damemi** [comment]
@vnl yeah, the manual process has steps that require the project name in the commands.

So it looks like it is just an issue with the Cloud Build steps. it's weird that it works the first time then fails on following attempts with `not found`. I would think it would be the other way around (that maybe the repository doesn't exist on the first attempt, then gets created and it works subsequently).

**Comment by ymotongpoo** [comment]
Thank you @vnl and @damemi for running and testing the code. I assume the causes of this issues are either of:

* the service account created for this demo doesn't have proper permissions
* container registry is not created somehow

**Comment by ymotongpoo** [comment]
@damemi I made a patch. Could you check the PR #16?

**Comment by damemi** [comment]
@vnl, could you please check if the latest code from https://github.com/GoogleCloudPlatform/opentelemetry-cloud-run/pull/16 fixes your issue?
